name: Neva-divers site (jekyll) BUILD TEST

# если push или pull в ветку main
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE.txt'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - 'LICENSE.txt'
    branches:
      - main

jobs:
  build-test:
    if: ${{ github.repository == 'NevaDivers/neva-divers.github.io' }}
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE должно быть задано на уровне задания, то есть для всех этапов
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Не требуется при использовании файла .ruby-version
          bundler-cache: true 
      - name: Build test
        run: |
          JEKYLL_ENV=production bundle exec jekyll build --safe
          echo "Completed."
        shell: bash
